apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
    annotations:
      # Replace ${PROJECT_ID?} with your project ID
      cnrm.cloud.google.com/project-id: "project_id" # kpt-set: ${project-id}
    name: devrole
    namespace: project-id # kpt-set: ${project-id}
spec:
    title: This Project-Level Dev Custom Role
    description: This role only contains dev relatd permissions
    permissions:
      - iam.roles.get
      - iam.roles.list
      - storage.buckets.delete
      - storage.buckets.get
      - storage.buckets.list
      - storage.buckets.create
      - storage.buckets.update
      - storage.objects.list
      - storage.objects.create
      - storage.objects.update
    stage: GA
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
    annotations:
      # Replace ${PROJECT_ID?} with your project ID
      cnrm.cloud.google.com/project-id: "project_id" # kpt-set: ${project-id}
    name: viewerrole
    namespace: project-id # kpt-set: ${project-id}
spec:
    title: This Project-Level Dev Custom Role
    description: This role only contains dev relatd permissions
    permissions:
      - iam.roles.get
      - iam.roles.list
      - storage.buckets.get
      - storage.buckets.list
      - storage.objects.get
      - storage.objects.list
    stage: GA
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
    annotations:
      # Replace ${PROJECT_ID?} with your project ID
      cnrm.cloud.google.com/project-id: "project_id" # kpt-set: ${project-id}
    name: adminrole
    namespace: project-id # kpt-set: ${project-id}
spec:
    title: This Project-Level Dev Custom Role
    description: This role only contains dev relatd permissions
    permissions:
      - roles/storage.admin
      - roles/monitoring.admin
      - roles/iam.admin
    stage: GA

 