apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
    name: admin-binding-project-id # kpt-set: admin-binding-${project-id}
    namespace: project-namespace # kpt-set: ${project-namespace}
spec:
    # Replace ${PROJECT_ID?} with your project ID
    member: "group:system-admin-group" # kpt-set: group:${system-admin-group}
    # Replace ${PROJECT_ID?} with your project ID
    resourceRef:
     apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
     kind: Project
     external: projects/my-project-id # kpt-set: projects/${project-id}
    role: roles/owner
---
