apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: admin-binding-project-id # kpt-set: admin-binding-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: roles/owner
      members:
        - member: "group:system-admin-group" # kpt-set: group:${system-admin-group}