apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
    annotations:
      # use the deletion policy of abandon to ensure that the pubsub service remains enabled when this resource is deleted.
      cnrm.cloud.google.com/deletion-policy: "abandon"
      # this is unnecessary with the deletion-policy of 'abandon', but useful if the abandon policy is removed.
      cnrm.cloud.google.com/disable-dependent-services: "false"
    name: logging.googleapis.com
    projectRef:
      external: "projects/project_id" # kpt-set: projects/${project-id}
  ---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
    annotations:
      # use the deletion policy of abandon to ensure that the pubsub service remains enabled when this resource is deleted.
      cnrm.cloud.google.com/deletion-policy: "abandon"
      # this is unnecessary with the deletion-policy of 'abandon', but useful if the abandon policy is removed.
      cnrm.cloud.google.com/disable-dependent-services: "false"
    name: monitoringe.googleapis.com
    projectRef:
      external: "projects/project_id" # kpt-set: projects/${project-id}
# To DO: append other service API needs to be enabled
