# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
    annotations:
      # Replace ${PROJECT_ID?} with your project ID
      cnrm.cloud.google.com/project-id: "project_id" # kpt-set: ${project-id}
    name: entitlerolesample1project-number # kpt-set: entitlerolesample1${project-number}
    namespace: project-namespace # kpt-set: ${project-namespace}
spec:
    title: Sample table level Custom Role
    description: Data Viewer Custom Role
    permissions:
      - bigquery.tables.createSnapshot
      - bigquery.tables.export
      - bigquery.tables.get
      - bigquery.tables.list
      - bigquery.tables.getData
      - bigquery.rowAccessPolicies.getFilteredData
    stage: GA
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: ent-sample1-binding-project-id # kpt-set: ent-sample1-binding-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
    kind: BigQueryTable
    name: bq-datatable-name-encypted-project-id # kpt-set: ${bq-datatable-name}-encrypted-${project-id}
    namespace: project-namespace # kpt-set: ${project-namespace}
  bindings:
    - role: projects/project-id/roles/entitlerolesample1project-number # kpt-set: projects/${project-id}/roles/entitlerolesample1${project-number}
      members:
        - member: "group:data-entitlement-group" # kpt-set: group:${data-entitlement-group}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: ent-sample2-binding-project-id # kpt-set: ent-sample2-binding-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
    kind: BigQueryTable
    name: bq-datatable-name-external-project-id # kpt-set: ${bq-datatable-name}-external-${project-id}
    namespace: project-namespace # kpt-set: ${project-namespace}
  bindings:
    - role: projects/project-id/roles/entitlerolesample1project-number # kpt-set: projects/${project-id}/roles/entitlerolesample1${project-number}
      members:
        - member: "group:data-entitlement-group" # kpt-set: group:${data-entitlement-group}

