apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: data-admin-binding-project-id # kpt-set: data-admin-binding-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: projects/project-id/roles/dataadminroleproject-number # kpt-set: projects/${project-id}/roles/dataadminrole${project-number}
      members:
        - member: "group:data-admin-group" # kpt-set: group:${data-admin-group}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: data-editor-binding-project-id # kpt-set: data-editor-binding-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: projects/project-id/roles/dataeditorroleproject-number # kpt-set: projects/${project-id}/roles/dataeditorrole${project-number}
      members:
        - member: "group:data-editor-group" # kpt-set: group:${data-editor-group}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: data-viewer-binding-project-id # kpt-set: data-viewer-binding-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: projects/project-id/roles/datavierroleproject-number # kpt-set: projects/${project-id}/roles/dataviewerrole${project-number}
      members:
        - member: "group:data-viwer-group" # kpt-set: group:${data-viewer-group}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: project-access-project-id # kpt-set: project-access-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: roles/browser 
      members:
        - member: "group:data-viwer-group" # kpt-set: group:${data-viewer-group}
        - member: "group:data-editor-group" # kpt-set: group:${data-editor-group}
        - member: "group:data-admin-group" # kpt-set: group:${data-admin-group}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: data-job-binding-project-id # kpt-set: data-job-binding-${project-id}
  namespace: project-namespace # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: projects/project-id/roles/datajobroleproject-number # kpt-set: projects/${project-id}/roles/datajobrole${project-number}
      members:
        - member: "group:data-job-group" # kpt-set: group:${data-job-group}
---
