apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: data-admin-binding
  namespace: project-id # kpt-set: ${project-id}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: roles/dataadminrole
      members:
        - member: "group:data-admin-group" # kpt-set: group:${data-admin-group}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
    name: data-editor-binding
    namespace: project-id # kpt-set: ${project-id}
spec:
    # Replace ${PROJECT_ID?} with your project ID
    member: "group:data-editor-group" # kpt-set: group:${data-admin-group}
    # Replace ${PROJECT_ID?} with your project ID
    resourceRef:
     apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
     kind: Project
     external: projects/my-project-id # kpt-set: projects/${project-id}
    role: roles/editor
---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
    name: viewer-binding
    namespace: project-id # kpt-set: ${project-id}
spec:
    # Replace ${PROJECT_ID?} with your project ID
    member: "group:data-viewer-group" # kpt-set: group:${data-viewer-group}  
    resourceRef:
     apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
     kind: Project
     external: projects/my-project-id # kpt-set: projects/${project-id}
    role: roles/viewer
---