# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: sourcerepo.cnrm.cloud.google.com/v1beta1
kind: SourceRepoRepository
metadata: # kpt-merge: config-control/deployment-repo
  name: sky-team-name-deployment-repo # kpt-set: ${sky-team-name}-deployment-repo
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: csr-read-sky-team-name # kpt-set: csr-read-${sky-team-name}
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  displayName: csr-read-sky-team-name # kpt-set: csr-read-${sky-team-name}
---
# Provides read access to source repo for cloudbuild trigger
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/source-repo-cloudbuild-read
  name: source-repo-cloudbuild-read
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  bindings:
    - members:
        - member: serviceAccount:csr-read-sky-team-name@management-project-id.iam.gserviceaccount.com # kpt-set: csr-read-${sky-team-name}@${management-project-id}.iam.gserviceaccount.com
      role: roles/source.reader
  resourceRef:
    name: sky-team-name-deployment-repo # kpt-set: ${sky-team-name}-deployment-repo
    apiVersion: sourcerepo.cnrm.cloud.google.com/v1beta1
    kind: SourceRepoRepository
---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
  name: ns-reconciler-sky-team-name-binding # kpt-set: ns-reconciler-${sky-team-name}-binding
  namespace: config-control
spec:
  member: serviceAccount:management-project-id.svc.id.goog[config-management-system/ns-reconciler-sky-team-name] # kpt-set: serviceAccount:${management-project-id}.svc.id.goog[config-management-system/ns-reconciler-${sky-team-name}]
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: csr-read-sky-team-name # kpt-set: csr-read-${sky-team-name}
  role: roles/iam.workloadIdentityUser
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # ROOT_REPO/namespaces/NAMESPACE/sync-rolebinding.yaml
metadata:
  annotations:
  name: syncs-repo-binding-cnrm-admin
  namespace: sky-team-name # kpt-set: ${sky-team-name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # TODO - change this to prevent it from modifying the reposync and configsync object
  name: cnrm-admin
subjects:
- kind: ServiceAccount
  name: ns-reconciler-sky-team-name # kpt-set: ns-reconciler-${sky-team-name}
  namespace: config-management-system
---


#####################
# ROOT_REPO/namespaces/NAMESPACE/repo-sync.yaml
# If you are using a Config Sync version earlier than 1.8.0,
# use: apiVersion: configsync.gke.io/v1alpha1
apiVersion: configsync.gke.io/v1beta1 #####################
kind: RepoSync
metadata:
  name: repo-sync
  namespace: sky-team-name # kpt-set: ${sky-team-name}
spec:
  git:
    auth: gcpserviceaccount
    branch: master
    gcpServiceAccountEmail: csr-read-sky-team-name@management-project-id.iam.gserviceaccount.com # kpt-set: csr-read-${sky-team-name}@${management-project-id}.iam.gserviceaccount.com
    repo: https://source.developers.google.com/p/management-project-id/r/sky-team-name-deployment-repo # kpt-set: https://source.developers.google.com/p/${management-project-id}/r/${sky-team-name}-deployment-repo
  # Since this is for a namespace repository, the format should be unstructured
  sourceFormat: unstructured
