apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: # kpt-merge: config-control/logging-sa-iam-permissions
  name: project-sa-iam-permissions
  namespace: project-id # kpt-set: ${project-id}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.4.0
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/project-id # kpt-set: projects/${project-id}
  bindings:
    - role: roles/owner
      members:
        - member: "serviceAccount:project-sa@project-id.iam.gserviceaccount.com" # kpt-set: serviceAccount:dev-sa@${project-id}.iam.gserviceaccount.com
