apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
    annotations:
      # Replace ${PROJECT_ID?} with your project ID
      cnrm.cloud.google.com/project-id: "project_id" # kpt-set: ${project-id}
    name: datajobrole
    namespace: project-id # kpt-set: ${project-id}
spec:
    title: Data Job Custom Role
    description: Data Job Custom Role
    permissions:
      - bigquery.jobs.create
      - bigquery.jobs.list
    stage: GA

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
    annotations:
      # Replace ${PROJECT_ID?} with your project ID
      cnrm.cloud.google.com/project-id: "project_id" # kpt-set: ${project-id}
    name: datareservationrole
    namespace: project-id # kpt-set: ${project-id}
spec:
    title: Slot Reservation Custom Role
    description: Slot Reservation Custom Role
    permissions:
      - bigquery.jobs.get
      - bigquery.jobs.list
      - bigquery.jobs.listAll
      - bigquery.reservations.create
      - bigquery.reservations.get
      - bigquery.reservations.delete
      - bigquery.reservations.update
      - bigquery.reservations.list
    stage: GA
---
